PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_tracked_subscription` (
	`id` integer PRIMARY KEY,
	`user_id` text REFERENCES `user`(`id`) ON DELETE set null,
	`service_name` text NOT NULL,
	`service_template_id` text,
	`plan_name` text,
	`service_url` text,
	`price_edited_by_user` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`color` text DEFAULT 'blue' NOT NULL,
	`icon_type` text DEFAULT 'preset' NOT NULL,
	`icon_value` text DEFAULT 'box' NOT NULL,
	`cycle` text NOT NULL,
	`amount` real NOT NULL,
	`currency` text DEFAULT 'JPY' NOT NULL,
	`first_payment_date` text NOT NULL,
	`next_billing_at` text NOT NULL,
	`days_until_next_billing` integer NOT NULL,
	`notify_days_before` integer DEFAULT 1 NOT NULL,
	`last_notified_at` integer,
	`last_notified_date` text,
	`canceled_at` integer,
	`cancellation_url` text,
	`cancellation_method` text,
	`cancellation_memo` text,
	`cancellation_deadline_memo` text,
	`tags` text NOT NULL,
	`is_sample` integer DEFAULT false NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);--> statement-breakpoint
INSERT INTO `__new_tracked_subscription` (
	`id`,
	`user_id`,
	`service_name`,
	`service_template_id`,
	`plan_name`,
	`service_url`,
	`price_edited_by_user`,
	`status`,
	`color`,
	`icon_type`,
	`icon_value`,
	`cycle`,
	`amount`,
	`currency`,
	`first_payment_date`,
	`next_billing_at`,
	`days_until_next_billing`,
	`notify_days_before`,
	`last_notified_at`,
	`last_notified_date`,
	`canceled_at`,
	`cancellation_url`,
	`cancellation_method`,
	`cancellation_memo`,
	`cancellation_deadline_memo`,
	`tags`,
	`is_sample`,
	`updated_at`,
	`created_at`
)
SELECT
	`id`,
	`user_id`,
	`service_name`,
	`service_template_id`,
	`plan_name`,
	`service_url`,
	`price_edited_by_user`,
	`status`,
	`color`,
	`icon_type`,
	`icon_value`,
	`cycle`,
	CAST(`amount` AS REAL),
	`currency`,
	`first_payment_date`,
	`next_billing_at`,
	`days_until_next_billing`,
	`notify_days_before`,
	`last_notified_at`,
	`last_notified_date`,
	`canceled_at`,
	`cancellation_url`,
	`cancellation_method`,
	`cancellation_memo`,
	`cancellation_deadline_memo`,
	`tags`,
	`is_sample`,
	`updated_at`,
	`created_at`
FROM `tracked_subscription`;--> statement-breakpoint
DROP TABLE `tracked_subscription`;--> statement-breakpoint
ALTER TABLE `__new_tracked_subscription` RENAME TO `tracked_subscription`;--> statement-breakpoint
PRAGMA foreign_keys=ON;
