PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`role` text DEFAULT 'user',
	`locale` text DEFAULT 'ja' NOT NULL,
	`time_zone` text DEFAULT 'Asia/Tokyo' NOT NULL,
	`active_theme` text DEFAULT 'rose' NOT NULL,
	`default_notify_days_before` integer DEFAULT 3 NOT NULL,
	`default_notify_time` text DEFAULT '09:00' NOT NULL,
	`notification_method` text DEFAULT 'email' NOT NULL,
	`onboarding_completed` integer DEFAULT false NOT NULL,
	`subscription_management_items_seeded` integer DEFAULT false NOT NULL,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`two_factor_enabled` integer DEFAULT false NOT NULL,
	`stripe_customer_id` text
);
--> statement-breakpoint
INSERT INTO `__new_user` (
	`id`,
	`name`,
	`email`,
	`email_verified`,
	`image`,
	`created_at`,
	`updated_at`,
	`role`,
	`locale`,
	`time_zone`,
	`active_theme`,
	`default_notify_days_before`,
	`default_notify_time`,
	`notification_method`,
	`onboarding_completed`,
	`subscription_management_items_seeded`,
	`banned`,
	`ban_reason`,
	`ban_expires`,
	`two_factor_enabled`,
	`stripe_customer_id`
)
SELECT
	`id`,
	`name`,
	`email`,
	`email_verified`,
	`image`,
	`created_at`,
	`updated_at`,
	`role`,
	`locale`,
	`time_zone`,
	`active_theme`,
	`default_notify_days_before`,
	`default_notify_time`,
	`notification_method`,
	`onboarding_completed`,
	`subscription_management_items_seeded`,
	`banned`,
	`ban_reason`,
	`ban_expires`,
	`two_factor_enabled`,
	`stripe_customer_id`
FROM `user`;--> statement-breakpoint
DROP TABLE `user`;--> statement-breakpoint
ALTER TABLE `__new_user` RENAME TO `user`;--> statement-breakpoint
CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);--> statement-breakpoint
CREATE TABLE `__new_tracked_subscription` (
	`id` integer PRIMARY KEY,
	`user_id` text REFERENCES `user`(`id`) ON DELETE set null,
	`category_id` integer REFERENCES `subscription_category`(`id`) ON DELETE set null,
	`payment_method_id` integer REFERENCES `subscription_payment_method`(`id`) ON DELETE set null,
	`service_name` text NOT NULL,
	`service_template_id` text,
	`plan_name` text,
	`service_url` text,
	`price_edited_by_user` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`color` text DEFAULT 'blue' NOT NULL,
	`icon_type` text DEFAULT 'preset' NOT NULL,
	`icon_value` text DEFAULT 'box' NOT NULL,
	`cycle` text NOT NULL,
	`amount` real NOT NULL,
	`currency` text DEFAULT 'JPY' NOT NULL,
	`first_payment_date` text NOT NULL,
	`next_billing_at` text NOT NULL,
	`days_until_next_billing` integer NOT NULL,
	`notify_days_before` integer DEFAULT 1 NOT NULL,
	`last_notified_at` integer,
	`last_notified_date` text,
	`canceled_at` integer,
	`cancellation_url` text,
	`cancellation_method` text,
	`cancellation_memo` text,
	`cancellation_deadline_memo` text,
	`tags` text NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);--> statement-breakpoint
INSERT INTO `__new_tracked_subscription` (
	`id`,
	`user_id`,
	`category_id`,
	`payment_method_id`,
	`service_name`,
	`service_template_id`,
	`plan_name`,
	`service_url`,
	`price_edited_by_user`,
	`status`,
	`color`,
	`icon_type`,
	`icon_value`,
	`cycle`,
	`amount`,
	`currency`,
	`first_payment_date`,
	`next_billing_at`,
	`days_until_next_billing`,
	`notify_days_before`,
	`last_notified_at`,
	`last_notified_date`,
	`canceled_at`,
	`cancellation_url`,
	`cancellation_method`,
	`cancellation_memo`,
	`cancellation_deadline_memo`,
	`tags`,
	`updated_at`,
	`created_at`
)
SELECT
	`id`,
	`user_id`,
	`category_id`,
	`payment_method_id`,
	`service_name`,
	`service_template_id`,
	`plan_name`,
	`service_url`,
	`price_edited_by_user`,
	`status`,
	`color`,
	`icon_type`,
	`icon_value`,
	`cycle`,
	`amount`,
	`currency`,
	`first_payment_date`,
	`next_billing_at`,
	`days_until_next_billing`,
	`notify_days_before`,
	`last_notified_at`,
	`last_notified_date`,
	`canceled_at`,
	`cancellation_url`,
	`cancellation_method`,
	`cancellation_memo`,
	`cancellation_deadline_memo`,
	`tags`,
	`updated_at`,
	`created_at`
FROM `tracked_subscription`
WHERE COALESCE(`is_sample`, 0) = 0;--> statement-breakpoint
DROP TABLE `tracked_subscription`;--> statement-breakpoint
ALTER TABLE `__new_tracked_subscription` RENAME TO `tracked_subscription`;--> statement-breakpoint
PRAGMA foreign_keys=ON;
